/**
 * Global constants for use in other scripts
 */

/**
 * MARK: Spawn Eggs
 * This is a list of all spawn eggs. Disabled ones are commented out
 */
global.allowed_eggs = {
	"minecraft:allay": "minecraft:allay_spawn_egg",
	"minecraft:axolotl": "minecraft:axolotl_spawn_egg",
	"minecraft:bat": "minecraft:bat_spawn_egg",
	"minecraft:bee": "minecraft:bee_spawn_egg",
	"minecraft:blaze": "minecraft:blaze_spawn_egg",
	"minecraft:cat": "minecraft:cat_spawn_egg",
	"minecraft:cave_spider": "minecraft:cave_spider_spawn_egg",
	"minecraft:chicken": "minecraft:chicken_spawn_egg",
	"minecraft:cod": "minecraft:cod_spawn_egg",
	"minecraft:cow": "minecraft:cow_spawn_egg",
	"minecraft:creeper": "minecraft:creeper_spawn_egg",
	"minecraft:dolphin": "minecraft:dolphin_spawn_egg",
	"minecraft:donkey": "minecraft:donkey_spawn_egg",
	"minecraft:drowned": "minecraft:drowned_spawn_egg",
	//"minecraft:elder_guardian": "minecraft_elder_guardian_spawn_egg", // Disabled: boss mob
	"minecraft:enderman": "minecraft:enderman_spawn_egg",
	"minecraft:endermite": "minecraft:endermite_spawn_egg",
	//"minecraft:evoker": "minecraft:evoker_spawn_egg", // Disabled: op totem farm
	"minecraft:fox": "minecraft:fox_spawn_egg",
	"minecraft:frog": "minecraft:frog_spawn_egg",
	"minecraft:ghast": "minecraft:ghast_spawn_egg",
	"minecraft:glow_squid": "minecraft:glow_squid_spawn_egg",
	"minecraft:goat": "minecraft:goat_spawn_egg",
	"minecraft:guardian": "minecraft:guardian_spawn_egg",
	"minecraft:hoglin": "minecraft:hoglin_spawn_egg",
	"minecraft:horse": "minecraft:horse_spawn_egg",
	"minecraft:husk": "minecraft:husk_spawn_egg",
	"minecraft:llama": "minecraft:llama_spawn_egg",
	"minecraft:magma_cube": "minecraft:magma_cube_spawn_egg",
	"minecraft:mooshroom": "minecraft:mooshroom_spawn_egg",
	"minecraft:mule": "minecraft:mule_spawn_egg",
	"minecraft:ocelot": "minecraft:ocelot_spawn_egg",
	"minecraft:panda": "minecraft:panda_spawn_egg",
	"minecraft:parrot": "minecraft:parrot_spawn_egg",
	"minecraft:phantom": "minecraft:phantom_spawn_egg",
	"minecraft:pig": "minecraft:pig_spawn_egg",
	"minecraft:piglin": "minecraft:piglin_spawn_egg",
	"minecraft:piglin_brute": "minecraft:piglin_brute_spawn_egg",
	"minecraft:pillager": "minecraft:pillager_spawn_egg",
	"minecraft:polar_bear": "minecraft:polar_bear_spawn_egg",
	"minecraft:pufferfish": "minecraft:pufferfish_spawn_egg",
	"minecraft:rabbit": "minecraft:rabbit_spawn_egg",
	"minecraft:ravager": "minecraft:ravager_spawn_egg",
	"minecraft:salmon": "minecraft:salmon_spawn_egg",
	"minecraft:sheep": "minecraft:sheep_spawn_egg",
	"minecraft:shulker": "minecraft:shulker_spawn_egg",
	"minecraft:silverfish": "minecraft:silverfish_spawn_egg",
	"minecraft:skeleton": "minecraft:skeleton_spawn_egg",
	"minecraft:skeleton_horse": "minecraft:skeleton_horse_spawn_egg",
	"minecraft:slime": "minecraft:slime_spawn_egg",
	"minecraft:spider": "minecraft:spider_spawn_egg",
	"minecraft:squid": "minecraft:squid_spawn_egg",
	"minecraft:stray": "minecraft:stray_spawn_egg",
	"minecraft:strider": "minecraft:strider_spawn_egg",
	"minecraft:tadpole": "minecraft:tadpole_spawn_egg",
	"minecraft:trader_llama": "minecraft:trader_llama_spawn_egg",
	"minecraft:tropical_fish": "minecraft:tropical_fish_spawn_egg",
	"minecraft:turtle": "minecraft:turtle_spawn_egg",
	"minecraft:vex": "minecraft:vex_spawn_egg",
	//"minecraft:villager": "minecraft:villager_spawn_egg", // Disabled: infinite trader
	"minecraft:vindicator": "minecraft:vindicator_spawn_egg",
	//"minecraft:wandering_trader": "minecraft:wandering_trader_spawn_egg", // Disabled: infinite trader
	//"minecraft:warden": "minecraft:warden_spawn_egg", // Disabled: griefing
	"minecraft:witch": "minecraft:witch_spawn_egg",
	"minecraft:wither_skeleton": "minecraft:wither_skeleton_spawn_egg",
	"minecraft:wolf": "minecraft:wolf_spawn_egg",
	"minecraft:zoglin": "minecraft:zoglin_spawn_egg",
	"minecraft:zombie": "minecraft:zombie_spawn_egg",
	"minecraft:zombie_horse": "minecraft:zombie_horse_spawn_egg",
	//"minecraft:zombie_villager": "minecraft:zombie_villager_spawn_egg", // Disabled: infinite trader
	"minecraft:zombified_piglin": "minecraft:zombified_piglin_spawn_egg",

	"alexsmobs:alligator_snapping_turtle": "alexsmobs:spawn_egg_alligator_snapping_turtle",
	"alexsmobs:anaconda": "alexsmobs:spawn_egg_anaconda",
	"alexsmobs:anteater": "alexsmobs:spawn_egg_anteater",
	"alexsmobs:bald_eagle": "alexsmobs:spawn_egg_bald_eagle",
	"alexsmobs:banana_slug": "alexsmobs:spawn_egg_banana_slug",
	"alexsmobs:bison": "alexsmobs:spawn_egg_bison",
	"alexsmobs:blobfish": "alexsmobs:spawn_egg_blobfish",
	"alexsmobs:blue_jay": "alexsmobs:spawn_egg_blue_jay",
	//"alexsmobs:bone_serpent": "alexsmobs:spawn_egg_bone_serpent", // Disabled: griefing
	"alexsmobs:bunfungus": "alexsmobs:spawn_egg_bunfungus",
	//"alexsmobs:cachalot_whale": "alexsmobs:spawn_egg_cachalot_whale", // Disabled: griefing
	"alexsmobs:capuchin_monkey": "alexsmobs:spawn_egg_capuchin_monkey",
	//"alexsmobs:catfish": "alexsmobs:spawn_egg_catfish", // Disabled: catfish are causing problems atm
	"alexsmobs:centipede_head": "alexsmobs:spawn_egg_centipede",
	"alexsmobs:cockroach": "alexsmobs:spawn_egg_cockroach",
	"alexsmobs:comb_jelly": "alexsmobs:spawn_egg_comb_jelly",
	"alexsmobs:cosmaw": "alexsmobs:spawn_egg_cosmaw",
	"alexsmobs:cosmic_cod": "alexsmobs:spawn_egg_cosmic_cod",
	"alexsmobs:crimson_mosquito": "alexsmobs:spawn_egg_crimson_mosquito",
	"alexsmobs:crocodile": "alexsmobs:spawn_egg_crocodile",
	"alexsmobs:crow": "alexsmobs:spawn_egg_crow",
	//"alexsmobs:devils_hole_pupfish": "alexsmobs:spawn_egg_devils_hole_pupfish", // Disabled: supposed to be rare
	"alexsmobs:dropbear": "alexsmobs:spawn_egg_dropbear",
	"alexsmobs:elephant": "alexsmobs:spawn_egg_elephant",
	"alexsmobs:emu": "alexsmobs:spawn_egg_emu",
	"alexsmobs:endergrade": "alexsmobs:spawn_egg_endergrade",
	"alexsmobs:enderiophage": "alexsmobs:spawn_egg_enderiophage",
	//"alexsmobs:farseer": "alexsmobs:spawn_egg_farseer", // Disabled: griefing
	"alexsmobs:flutter": "alexsmobs:spawn_egg_flutter",
	"alexsmobs:fly": "alexsmobs:spawn_egg_fly",
	"alexsmobs:flying_fish": "alexsmobs:spawn_egg_flying_fish",
	"alexsmobs:frilled_shark": "alexsmobs:spawn_egg_frilled_shark",
	"alexsmobs:froststalker": "alexsmobs:spawn_egg_froststalker",
	"alexsmobs:gazelle": "alexsmobs:spawn_egg_gazelle",
	"alexsmobs:gelada_monkey": "alexsmobs:spawn_egg_gelada_monkey",
	"alexsmobs:giant_squid": "alexsmobs:spawn_egg_giant_squid",
	"alexsmobs:gorilla": "alexsmobs:spawn_egg_gorilla",
	"alexsmobs:grizzly_bear": "alexsmobs:spawn_egg_grizzly_bear",
	"alexsmobs:guster": "alexsmobs:spawn_egg_guster",
	"alexsmobs:hammerhead_shark": "alexsmobs:spawn_egg_hammerhead_shark",
	"alexsmobs:hummingbird": "alexsmobs:spawn_egg_hummingbird",
	"alexsmobs:jerboa": "alexsmobs:spawn_egg_jerboa",
	"alexsmobs:kangaroo": "alexsmobs:spawn_egg_kangaroo",
	"alexsmobs:komodo_dragon": "alexsmobs:spawn_egg_komodo_dragon",
	"alexsmobs:laviathan": "alexsmobs:spawn_egg_laviathan",
	"alexsmobs:leafcutter_ant": "alexsmobs:spawn_egg_leafcutter_ant",
	"alexsmobs:lobster": "alexsmobs:spawn_egg_lobster",
	"alexsmobs:maned_wolf": "alexsmobs:spawn_egg_maned_wolf",
	"alexsmobs:mantis_shrimp": "alexsmobs:spawn_egg_mantis_shrimp",
	"alexsmobs:mimic_octopus": "alexsmobs:spawn_egg_mimic_octopus",
	//"alexsmobs:mimicube": "alexsmobs:spawn_egg_mimicube", // Disabled: op mimicream farm
	"alexsmobs:moose": "alexsmobs:spawn_egg_moose",
	"alexsmobs:mudskipper": "alexsmobs:spawn_egg_mudskipper",
	"alexsmobs:mungus": "alexsmobs:spawn_egg_mungus",
	"alexsmobs:murmur": "alexsmobs:spawn_egg_murmur",
	"alexsmobs:orca": "alexsmobs:spawn_egg_orca",
	"alexsmobs:platypus": "alexsmobs:spawn_egg_platypus",
	"alexsmobs:potoo": "alexsmobs:spawn_egg_potoo",
	"alexsmobs:raccoon": "alexsmobs:spawn_egg_raccoon",
	"alexsmobs:rain_frog": "alexsmobs:spawn_egg_rain_frog",
	"alexsmobs:rattlesnake": "alexsmobs:spawn_egg_rattlesnake",
	"alexsmobs:rhinoceros": "alexsmobs:spawn_egg_rhinoceros",
	"alexsmobs:roadrunner": "alexsmobs:spawn_egg_roadrunner",
	"alexsmobs:rocky_roller": "alexsmobs:spawn_egg_rocky_roller",
	"alexsmobs:seagull": "alexsmobs:spawn_egg_seagull",
	"alexsmobs:seal": "alexsmobs:spawn_egg_seal",
	"alexsmobs:shoebill": "alexsmobs:spawn_egg_shoebill",
	"alexsmobs:skelewag": "alexsmobs:spawn_egg_skelewag",
	"alexsmobs:skreecher": "alexsmobs:spawn_egg_skreecher",
	"alexsmobs:skunk": "alexsmobs:spawn_egg_skunk",
	"alexsmobs:snow_leopard": "alexsmobs:spawn_egg_snow_leopard",
	"alexsmobs:soul_vulture": "alexsmobs:spawn_egg_soul_vulture",
	"alexsmobs:spectre": "alexsmobs:spawn_egg_spectre",
	"alexsmobs:straddler": "alexsmobs:spawn_egg_straddler",
	"alexsmobs:stradpole": "alexsmobs:spawn_egg_stradpole",
	"alexsmobs:sugar_glider": "alexsmobs:spawn_egg_sugar_glider",
	//"alexsmobs:sunbird": "alexsmobs:spawn_egg_sunbird", // Disabled: supposed to be rare
	"alexsmobs:tarantula_hawk": "alexsmobs:spawn_egg_tarantula_hawk",
	"alexsmobs:tasmanian_devil": "alexsmobs:spawn_egg_tasmanian_devil",
	"alexsmobs:terrapin": "alexsmobs:spawn_egg_terrapin",
	"alexsmobs:tiger": "alexsmobs:spawn_egg_tiger",
	"alexsmobs:toucan": "alexsmobs:spawn_egg_toucan",
	"alexsmobs:tusklin": "alexsmobs:spawn_egg_tusklin",
	"alexsmobs:underminer": "alexsmobs:spawn_egg_underminer",
	//"alexsmobs:void_worm": "alexsmobs:spawn_egg_void_worm", // Disabled: boss mob
	//"alexsmobs:warped_mosco": "alexsmobs:spawn_egg_warped_mosco", // Disabled: boss mob
	"alexsmobs:warped_toad": "alexsmobs:spawn_egg_warped_toad",

	//"aquaculture:arrau_turtle": "aquaculture:arrau_turtle_spawn_egg", // Disabled: mob is disabled
	//"aquaculture:box_turtle": "aquaculture:box_turtle_spawn_egg", // Disabled: mob is disabled
	//"aquaculture:starshell_turtle": "aquaculture:starshell_turtle_spawn_egg", // Disabled: mob is disabled

	//"ars_nouveau:drygmy": "ars_nouveau:drygmy_se", // Disabled: supposed to find in wild
	//"ars_nouveau:starbuncle": "ars_nouveau:starbuncle_se", // Disabled: supposed to find in wild
	//"ars_nouveau:whirlisprig": "ars_nouveau:whirlisprig_se", // Disabled: supposed to find in wild
	"ars_nouveau:wilden_guardian": "ars_nouveau:wilden_guardian_se",
	"ars_nouveau:wilden_hunter": "ars_nouveau:wilden_hunter_se",
	"ars_nouveau:wilden_stalker": "ars_nouveau:wilden_stalker_se",

	"babyfat:ranchu": "babyfat:ranchu_spawn_egg",

	"cnb:cactem": "cnb:cactem_spawn_egg",
	"cnb:cindershell": "cnb:cindershell_spawn_egg",
	"cnb:end_whale": "cnb:end_whale_spawn_egg",
	"cnb:lilytad": "cnb:lilytad_spawn_egg",
	"cnb:little_grebe": "cnb:little_grebe_spawn_egg",
	"cnb:lizard": "cnb:lizard_spawn_egg",
	"cnb:minipad": "cnb:minipad_spawn_egg",
	// sporelings have special implementation, see below
	"cnb:yeti": "cnb:yeti_spawn_egg",

	"creeperoverhaul:badlands_creeper": "creeperoverhaul:badlands_creeper_spawn_egg",
	"creeperoverhaul:bamboo_creeper": "creeperoverhaul:bamboo_creeper_spawn_egg",
	"creeperoverhaul:beach_creeper": "creeperoverhaul:beach_creeper_spawn_egg",
	"creeperoverhaul:cave_creeper": "creeperoverhaul:cave_creeper_spawn_egg",
	"creeperoverhaul:dark_oak_creeper": "creeperoverhaul:dark_oak_creeper_spawn_egg",
	"creeperoverhaul:desert_creeper": "creeperoverhaul:desert_creeper_spawn_egg",
	"creeperoverhaul:dripstone_creeper": "creeperoverhaul:dripstone_creeper_spawn_egg",
	"creeperoverhaul:hills_creeper": "creeperoverhaul:hills_creeper_spawn_egg",
	"creeperoverhaul:jungle_creeper": "creeperoverhaul:jungle_creeper_spawn_egg",
	"creeperoverhaul:mushroom_creeper": "creeperoverhaul:mushroom_creeper_spawn_egg",
	"creeperoverhaul:ocean_creeper": "creeperoverhaul:ocean_creeper_spawn_egg",
	"creeperoverhaul:savannah_creeper": "creeperoverhaul:savannah_creeper_spawn_egg",
	"creeperoverhaul:snowy_creeper": "creeperoverhaul:snowy_creeper_spawn_egg",
	"creeperoverhaul:spruce_creeper": "creeperoverhaul:spruce_creeper_spawn_egg",
	"creeperoverhaul:swamp_creeper": "creeperoverhaul:swamp_creeper_spawn_egg",

	"crittersandcompanions:dragonfly": "crittersandcompanions:dragonfly_spawn_egg",
	"crittersandcompanions:dumbo_octopus": "crittersandcompanions:dumbo_octopus_spawn_egg",
	"crittersandcompanions:ferret": "crittersandcompanions:ferret_spawn_egg",
	"crittersandcompanions:jumping_spider":
		"crittersandcompanions:jumping_spider_spawn_egg",
	"crittersandcompanions:koi_fish": "crittersandcompanions:koi_fish_spawn_egg",
	"crittersandcompanions:leaf_insect": "crittersandcompanions:leaf_insect_spawn_egg",
	"crittersandcompanions:otter": "crittersandcompanions:otter_spawn_egg",
	"crittersandcompanions:red_panda": "crittersandcompanions:red_panda_spawn_egg",
	"crittersandcompanions:sea_bunny": "crittersandcompanions:sea_bunny_spawn_egg",
	"crittersandcompanions:shima_enaga": "crittersandcompanions:shima_enaga_spawn_egg",

	"deeperdarker:sculk_centipede": "deeperdarker:sculk_centipede_spawn_egg",
	"deeperdarker:sculk_leech": "deeperdarker:sculk_leech_spawn_egg",
	"deeperdarker:sculk_snapper": "deeperdarker:sculk_snapper_spawn_egg",
	"deeperdarker:shattered": "deeperdarker:shattered_spawn_egg",
	"deeperdarker:shriek_worm": "deeperdarker:shriek_worm_spawn_egg",
	"deeperdarker:stalker": "deeperdarker:stalker_spawn_egg",

	"duckling:duck": "duckling:duck_spawn_egg",
	//"duckling:quackling": "duckling:quackling_spawn_egg", // Disabled: infinite traders

	"ecologics:camel": "ecologics:camel_spawn_egg",
	"ecologics:coconut_crab": "ecologics:coconut_crab_spawn_egg",
	"ecologics:penguin": "ecologics:penguin_spawn_egg",
	"ecologics:squirrel": "ecologics:squirrel_spawn_egg",

	//"minecraft:iron_golem": "spawnermod:iron_golem_spawn_egg", // Disabled: op iron farm

	"environmental:deer": "environmental:deer_spawn_egg",
	"environmental:duck": "environmental:duck_spawn_egg",
	"environmental:koi": "environmental:koi_spawn_egg",
	"environmental:reindeer": "environmental:reindeer_spawn_egg",
	"environmental:slabfish": "environmental:slabfish_spawn_egg",
	"environmental:tapir": "environmental:tapir_spawn_egg",
	"environmental:yak": "environmental:yak_spawn_egg",
	"environmental:zebra": "environmental:zebra_spawn_egg",

	"extendedmushrooms:mushroom_sheep": "extendedmushrooms:mushroom_sheep_spawn_egg",

	//"friendsandfoes:copper_golem": "friendsandfoes:copper_golem_spawn_egg", // Disable: op copper farm
	"friendsandfoes:crab": "friendsandfoes:crab_spawn_egg",
	"friendsandfoes:glare": "friendsandfoes:glare_spawn_egg",
	//"friendsandfoes:iceologer": "friendsandfoes:iceologer_spawn_egg", // Disable: op totem farm
	//"friendsandfoes:illusioner": "friendsandfoes:illusioner_spawn_egg", // Disable: op totem farm
	//"friendsandfoes:mauler": "friendsandfoes:mauler_spawn_egg", // Disable: mob is disabled
	"friendsandfoes:moobloom": "friendsandfoes:moobloom_spawn_egg",
	//"friendsandfoes:rascal": "friendsandfoes:rascal_spawn_egg", // Disable: can't kill mob?
	//"friendsandfoes:tuff_golem": "friendsandfoes:tuff_golem_spawn_egg", // Disable: tuff can be crushed into metals
	//"friendsandfoes:wildfire": "friendsandfoes:wildfire_spawn_egg", // Disable: boss mob

	//"goblintraders:goblin_trader": "goblintraders:goblin_trader_spawn_egg", // Disable: infinite traders
	//"goblintraders:vein_goblin_trader": "goblintraders:vein_goblin_trader_spawn_egg", // Disable: infinite traders

	"hexerei:crow": "hexerei:crow_spawn_egg",
	"hexerei:owl": "hexerei:owl_spawn_egg",

	"kakapos:kakapo": "kakapos:kakapo_spawn_egg",

	"mythicmounts:acencia": "mythicmounts:acencia_spawn_egg",
	"mythicmounts:archelon": "mythicmounts:archelon_spawn_egg",
	"mythicmounts:colelytra": "mythicmounts:colelytra_spawn_egg",
	"mythicmounts:courierbird": "mythicmounts:courierbird_spawn_egg",
	"mythicmounts:direwolf": "mythicmounts:direwolf_spawn_egg",
	"mythicmounts:dragon": "mythicmounts:dragon_spawn_egg",
	"mythicmounts:firebird": "mythicmounts:firebird_spawn_egg",
	"mythicmounts:geckotoalizard": "mythicmounts:geckotoalizard_spawn_egg",
	"mythicmounts:griffon": "mythicmounts:griffon_spawn_egg",
	"mythicmounts:moth": "mythicmounts:moth_spawn_egg",
	"mythicmounts:netherbat": "mythicmounts:netherbat_spawn_egg",
	"mythicmounts:nightmare": "mythicmounts:nightmare_spawn_egg",
	"mythicmounts:nudibranch": "mythicmounts:nudibranch_spawn_egg",
	"mythicmounts:ridinglizard": "mythicmounts:ridinglizard_spawn_egg",

	"netherdepthsupgrade:blazefish": "netherdepthsupgrade:blazefish_spawn_egg",
	"netherdepthsupgrade:bonefish": "netherdepthsupgrade:bonefish_spawn_egg",
	"netherdepthsupgrade:eyeball_fish": "netherdepthsupgrade:eyeball_fish_spawn_egg",
	"netherdepthsupgrade:fortressgrouper": "netherdepthsupgrade:fortress_grouper_spawn_egg",
	"netherdepthsupgrade:glowdine": "netherdepthsupgrade:glowdine_spawn_egg",
	"netherdepthsupgrade:lava_pufferfish": "netherdepthsupgrade:lava_pufferfish_spawn_egg",
	"netherdepthsupgrade:magmacubefish": "netherdepthsupgrade:magmacubefish_spawn_egg",
	"netherdepthsupgrade:obsidianfish": "netherdepthsupgrade:obsidianfish_spawn_egg",
	"netherdepthsupgrade:searing_cod": "netherdepthsupgrade:searing_cod_spawn_egg",
	"netherdepthsupgrade:soulsucker": "netherdepthsupgrade:soulsucker_spawn_egg",
	"netherdepthsupgrade:wither_bonefish": "netherdepthsupgrade:wither_bonefish_spawn_egg",

	"byg:man_o_war": "byg:man_o_war_spawn_egg",
	"byg:pumpkin_warden": "byg:pumpkin_warden_spawn_egg",

	"quark:crab": "quark:crab_spawn_egg",
	"quark:forgotten": "quark:forgotten_spawn_egg",
	"quark:foxhound": "quark:foxhound_spawn_egg",
	"quark:shiba": "quark:shiba_spawn_egg",
	"quark:stoneling": "quark:stoneling_spawn_egg",
	"quark:toretoise": "quark:toretoise_spawn_egg",
	"quark:wraith": "quark:wraith_spawn_egg",

	"snuffles:snuffle": "snuffles:snuffle_spawn_egg",

	"sprout:bounce_bug": "sprout:bouncebug_spawn_egg",
	"sprout:elephant": "sprout:elephant_spawn_egg",

	"swampier_swamps:dragonfly": "swampier_swamps:dragonfly_spawn_egg",

	//"twilightforest:adherent": "twilightforest:adherent_spawn_egg", // Disabled: mob is NYI
	//"twilightforest:alpha_yeti": "twilightforest:alpha_yeti_spawn_egg", // Disabled: progression skip for tf
	//"twilightforest:armored_giant": "twilightforest:armored_giant_spawn_egg", // Disabled: progression skip for tf
	"twilightforest:bighorn_sheep": "twilightforest:bighorn_sheep_spawn_egg",
	"twilightforest:blockchain_goblin": "twilightforest:blockchain_goblin_spawn_egg",
	"twilightforest:boar": "twilightforest:boar_spawn_egg",
	"twilightforest:carminite_broodling": "twilightforest:carminite_broodling_spawn_egg",
	"twilightforest:carminite_ghastguard": "twilightforest:carminite_ghastguard_spawn_egg",
	"twilightforest:carminite_ghastling": "twilightforest:carminite_ghastling_spawn_egg",
	//"twilightforest:carminite_golem": "twilightforest:carminite_golem_spawn_egg", // Disabled: op iron farm
	"twilightforest:death_tome": "twilightforest:death_tome_spawn_egg",
	"twilightforest:deer": "twilightforest:deer_spawn_egg",
	"twilightforest:dwarf_rabbit": "twilightforest:dwarf_rabbit_spawn_egg",
	"twilightforest:fire_beetle": "twilightforest:fire_beetle_spawn_egg",
	//"twilightforest:giant_miner": "twilightforest:giant_miner_spawn_egg", // Disabled: progression skip for tf
	//"twilightforest:harbinger_cube": "twilightforest:harbinger_cube_spawn_egg" // Disabled: mob is NYI
	"twilightforest:hedge_spider": "twilightforest:hedge_spider_spawn_egg",
	"twilightforest:helmet_crab": "twilightforest:helmet_crab_spawn_egg",
	"twilightforest:hostile_wolf": "twilightforest:hostile_wolf_spawn_egg",
	//"twilightforest:hydra": "twilightforest:hydra_spawn_egg", // Disabled: boss mob
	"twilightforest:ice_crystal": "twilightforest:ice_crystal_spawn_egg",
	"twilightforest:king_spider": "twilightforest:king_spider_spawn_egg",
	//"twilightforest:knight_phantom": "twilightforest:knight_phantom_spawn_egg", // Disabled: boss mob
	"twilightforest:kobold": "twilightforest:kobold_spawn_egg",
	//"twilightforest:lich": "twilightforest:lich_spawn_egg", // Disabled: boss mob
	"twilightforest:lower_goblin_knight": "twilightforest:lower_goblin_knight_spawn_egg",
	"twilightforest:maze_slime": "twilightforest:maze_slime_spawn_egg",
	//"twilightforest:minoshroom": "twilightforest:minoshroom_spawn_egg", // Disabled: boss mob
	"twilightforest:minotaur": "twilightforest:minotaur_spawn_egg",
	"twilightforest:mist_wolf": "twilightforest:mist_wolf_spawn_egg",
	"twilightforest:mosquito_swarm": "twilightforest:mosquito_swarm_spawn_egg",
	//"twilightforest:naga": "twilightforest:naga_spawn_egg", // Disabled: boss mob
	"twilightforest:penguin": "twilightforest:penguin_spawn_egg",
	"twilightforest:pinch_beetle": "twilightforest:pinch_beetle_spawn_egg",
	//"twilightforest:quest_ram": "twilightforest:quest_ram_spawn_egg" // Disabled: op diamond farm
	"twilightforest:raven": "twilightforest:raven_spawn_egg",
	"twilightforest:redcap_sapper": "twilightforest:redcap_sapper_spawn_egg",
	"twilightforest:redcap": "twilightforest:redcap_spawn_egg",
	//"twilightforest:roving_cube": "twilightforest:roving_cube_spawn_egg", // Disabled: mob is NYI
	"twilightforest:skeleton_druid": "twilightforest:skeleton_druid_spawn_egg",
	"twilightforest:slime_beetle": "twilightforest:slime_beetle_spawn_egg",
	"twilightforest:snow_guardian": "twilightforest:snow_guardian_spawn_egg",
	//"twilightforest:snow_queen": "twilightforest:snow_queen_spawn_egg", // Disabled: boss mob
	"twilightforest:squirrel": "twilightforest:squirrel_spawn_egg",
	"twilightforest:stable_ice_core": "twilightforest:stable_ice_core_spawn_egg",
	"twilightforest:swarm_spider": "twilightforest:swarm_spider_spawn_egg",
	"twilightforest:tiny_bird": "twilightforest:tiny_bird_spawn_egg",
	"twilightforest:towerwood_borer": "twilightforest:towerwood_borer_spawn_egg",
	"twilightforest:troll": "twilightforest:troll_spawn_egg",
	"twilightforest:unstable_ice_core": "twilightforest:unstable_ice_core_spawn_egg",
	//"twilightforest:ur_ghast": "twilightforest:ur_ghast_spawn_egg", // Disabled: boss mob
	"twilightforest:winter_wolf": "twilightforest:winter_wolf_spawn_egg",
	"twilightforest:wraith": "twilightforest:wraith_spawn_egg",
	"twilightforest:yeti": "twilightforest:yeti_spawn_egg",
};

//MARK: Text Formatting
global.formatcodes = {
	black: `\u00A70`, // #000000
	dark_blue: `\u00A71`, // #0000AA
	dark_green: `\u00A72`, // #00AA00
	dark_aqua: `\u00A73`, // #00AAAA
	dark_red: `\u00A74`, // #AA0000
	dark_purple: `\u00A75`, // #AA00AA
	gold: `\u00A76`, // #FFAA00
	gray: `\u00A77`, // #AAAAAA
	dark_gray: `\u00A78`, // #555555
	blue: `\u00A79`, // #5555FF
	green: `\u00A7a`, // #55FF55
	aqua: `\u00A7b`, // #55FFFF
	red: `\u00A7c`, // #FF5555
	light_purple: `\u00A7d`, // #FF55FF
	yellow: `\u00A7e`, // #FFFF55
	white: `\u00A7f`, // #FFFFFF
	glitch: `\u00A7k`,
	bold: `\u00A7l`,
	strikethrough: `\u00A7m`,
	underline: `\u00A7n`,
	italic: `\u00A7o`,
	reset: `\u00A7r`,
};

//MARK: Dye Colors
global.dye_colors = [
	"white",
	"orange",
	"magenta",
	"light_blue",
	"yellow",
	"lime",
	"pink",
	"gray",
	"light_gray",
	"cyan",
	"purple",
	"blue",
	"brown",
	"green",
	"red",
	"black",
];

//MARK: Moons
global.hex_moons = {
	Pink: "April",
	Flower: "May",
	Strawberry: "June",
	Antler: "July",
	Harvest: "August",
	Corn: "September",
	Hunter: "December",
	Frost: "October",
	Oak: "November",
	Wolf: "January",
	Snow: "March",
	Worm: "February",
	Black: global.formatcodes.dark_gray + global.formatcodes.glitch + "NEVER",
};

//MARK: Coins
global.hex_coins = {
	Lunar: "UNCOMMON", // rarities
	Solar: "RARE",
	Arcane: "EPIC",
};

/**
 * MARK: Disabled Items
 * The items in these lists are hidden from JEI, uncraftable and cannot be found in loot.
 * They are also marked with a tooltip specifying they are unobtainable.
 */
global.disabled_items = [
	"aquaculture:acacia_fish_mount",
	"aquaculture:birch_fish_mount",
	"aquaculture:dark_oak_fish_mount",
	"aquaculture:jungle_fish_mount",
	"aquaculture:oak_fish_mount",
	"aquaculture:spruce_fish_mount",
	"artifacts:eternal_steak",
	"artifacts:everlasting_beef",
	"caupona:stock",
	"caupona:stock_aspic",
	"crittersandcompanions:diamond_dragonfly_armor",
	"crittersandcompanions:gold_dragonfly_armor",
	"crittersandcompanions:iron_dragonfly_armor",
	"delightful:animal_fat",
	"delightful:animal_oil_bottle",
	"delightful:cooked_venison_chops",
	"delightful:zinc_knife",
	"ends_delight:dragon_egg_shell_knife",
	"ends_delight:end_stone_knife",
	"ends_delight:purpur_knife",
	"enigmaticgraves:grave_finder",
	"environmental:cherries",
	"environmental:cherry_crate",
	"extradisks:256k_storage_block",
	"extradisks:1024k_storage_block",
	"extradisks:4096k_storage_block",
	"extradisks:16384k_fluid_storage_block",
	"extradisks:16384k_fluid_storage_disk",
	"extradisks:16384k_fluid_storage_part",
	"extradisks:16384k_storage_block",
	"extradisks:65536k_fluid_storage_block",
	"extradisks:65536k_fluid_storage_disk",
	"extradisks:65536k_fluid_storage_part",
	"extradisks:65536k_storage_block",
	"extradisks:262144k_fluid_storage_block",
	"extradisks:262144k_fluid_storage_disk",
	"extradisks:262144k_fluid_storage_part",
	"extradisks:262144k_storage_block",
	"extradisks:1048576k_fluid_storage_block",
	"extradisks:1048576k_fluid_storage_disk",
	"extradisks:1048576k_fluid_storage_part",
	"extradisks:1048576k_storage_block",
	"extradisks:infinite_fluid_storage_block",
	"extradisks:infinite_fluid_storage_disk",
	"extradisks:infinite_fluid_storage_part",
	"extradisks:infinite_storage_block",
	"farmersdelight:golden_knife",
	"farmingforblockheads:feeding_trough",
	"ftbquests:barrier",
	"ftbquests:custom_icon",
	"ftbquests:detector",
	"ftbquests:loot_crate_opener",
	"ftbquests:missing_item",
	"ftbquests:screen_1",
	"ftbquests:screen_3",
	"ftbquests:screen_5",
	"ftbquests:screen_7",
	"ftbquests:stage_barrier",
	"functionalstorage:armory_cabinet",
	"gildedarmor:gilded_enderite_boots",
	"gildedarmor:gilded_enderite_chestplate",
	"gildedarmor:gilded_enderite_helmet",
	"gildedarmor:gilded_enderite_leggings",
	"hexerei:milk_bottle",
	"incubation:fried_egg",
	"itemfilters:always_false",
	"itemfilters:always_true",
	"itemfilters:and",
	"itemfilters:block",
	"itemfilters:custom",
	"itemfilters:damage",
	"itemfilters:id_regex",
	"itemfilters:item_group",
	"itemfilters:max_count",
	"itemfilters:mod",
	"itemfilters:not",
	"itemfilters:or",
	"itemfilters:strong_nbt",
	"itemfilters:tag",
	"itemfilters:weak_nbt",
	"itemfilters:xor",
	"pipez:energy_pipe",
	"pipez:fluid_pipe",
	"pipez:gas_pipe",
	"pipez:universal_pipe",
	"prefab:block_boundary",
	"prefab:item_bunch_of_beets",
	"prefab:item_bunch_of_carrots",
	"prefab:item_bunch_of_potatoes",
	"prefab:item_clutch_of_eggs",
	"prefab:item_crate_of_beets",
	"prefab:item_crate_of_carrots",
	"prefab:item_crate_of_potatoes",
	"prefab:item_sickle_diamond",
	"prefab:item_sickle_gold",
	"prefab:item_sickle_iron",
	"prefab:item_sickle_netherite",
	"prefab:item_sickle_stone",
	"prefab:item_sickle_wood",
	"prefab:item_swift_blade_bronze",
	"prefab:item_swift_blade_copper",
	"prefab:item_swift_blade_diamond",
	"prefab:item_swift_blade_gold",
	"prefab:item_swift_blade_iron",
	"prefab:item_swift_blade_netherite",
	"prefab:item_swift_blade_obsidian",
	"prefab:item_swift_blade_osmium",
	"prefab:item_swift_blade_steel",
	"prefab:item_swift_blade_stone",
	"prefab:item_swift_blade_wood",
	"prefab:item_wooden_crate",
	"quark:beetroot_crate",
	"quark:carrot_crate",
	"quark:feeding_trough",
	"quark:potato_crate",
	"refinedstorage:1k_storage_block",
	"refinedstorage:4k_storage_block",
	"refinedstorage:16k_storage_block",
	"refinedstorage:64k_fluid_storage_block",
	"refinedstorage:64k_fluid_storage_disk",
	"refinedstorage:64k_fluid_storage_part",
	"refinedstorage:64k_storage_block",
	"refinedstorage:256k_fluid_storage_block",
	"refinedstorage:256k_fluid_storage_disk",
	"refinedstorage:256k_fluid_storage_part",
	"refinedstorage:1024k_fluid_storage_block",
	"refinedstorage:1024k_fluid_storage_disk",
	"refinedstorage:1024k_fluid_storage_part",
	"refinedstorage:4096k_fluid_storage_block",
	"refinedstorage:4096k_fluid_storage_disk",
	"refinedstorage:4096k_fluid_storage_part",
	"refinedstorage:black_controller",
	"refinedstorage:black_crafter",
	"refinedstorage:black_crafter_manager",
	"refinedstorage:black_crafting_monitor",
	"refinedstorage:black_fluid_grid",
	"refinedstorage:black_pattern_grid",
	"refinedstorage:blue_controller",
	"refinedstorage:blue_crafter",
	"refinedstorage:blue_crafter_manager",
	"refinedstorage:blue_crafting_monitor",
	"refinedstorage:blue_fluid_grid",
	"refinedstorage:blue_pattern_grid",
	"refinedstorage:brown_controller",
	"refinedstorage:brown_crafter",
	"refinedstorage:brown_crafter_manager",
	"refinedstorage:brown_crafting_monitor",
	"refinedstorage:brown_fluid_grid",
	"refinedstorage:brown_pattern_grid",
	"refinedstorage:constructor",
	"refinedstorage:controller",
	"refinedstorage:crafter",
	"refinedstorage:crafter_manager",
	"refinedstorage:crafting_monitor",
	"refinedstorage:crafting_upgrade",
	"refinedstorage:creative_fluid_storage_block",
	"refinedstorage:creative_fluid_storage_disk",
	"refinedstorage:creative_portable_grid",
	"refinedstorage:creative_storage_block",
	"refinedstorage:creative_storage_disk",
	"refinedstorage:creative_wireless_crafting_monitor",
	"refinedstorage:creative_wireless_fluid_grid",
	"refinedstorage:cyan_controller",
	"refinedstorage:cyan_crafter",
	"refinedstorage:cyan_crafter_manager",
	"refinedstorage:cyan_crafting_monitor",
	"refinedstorage:cyan_fluid_grid",
	"refinedstorage:cyan_pattern_grid",
	"refinedstorage:destructor",
	"refinedstorage:fluid_grid",
	"refinedstorage:fluid_interface",
	"refinedstorage:fortune_1_upgrade",
	"refinedstorage:fortune_2_upgrade",
	"refinedstorage:fortune_3_upgrade",
	"refinedstorage:gray_controller",
	"refinedstorage:gray_crafter",
	"refinedstorage:gray_crafter_manager",
	"refinedstorage:gray_crafting_monitor",
	"refinedstorage:gray_fluid_grid",
	"refinedstorage:gray_pattern_grid",
	"refinedstorage:green_controller",
	"refinedstorage:green_crafter",
	"refinedstorage:green_crafter_manager",
	"refinedstorage:green_crafting_monitor",
	"refinedstorage:green_fluid_grid",
	"refinedstorage:green_pattern_grid",
	"refinedstorage:light_gray_controller",
	"refinedstorage:light_gray_crafter",
	"refinedstorage:light_gray_crafter_manager",
	"refinedstorage:light_gray_crafting_monitor",
	"refinedstorage:light_gray_fluid_grid",
	"refinedstorage:light_gray_pattern_grid",
	"refinedstorage:lime_controller",
	"refinedstorage:lime_crafter",
	"refinedstorage:lime_crafter_manager",
	"refinedstorage:lime_crafting_monitor",
	"refinedstorage:lime_fluid_grid",
	"refinedstorage:lime_pattern_grid",
	"refinedstorage:magenta_controller",
	"refinedstorage:magenta_crafter",
	"refinedstorage:magenta_crafter_manager",
	"refinedstorage:magenta_crafting_monitor",
	"refinedstorage:magenta_fluid_grid",
	"refinedstorage:magenta_pattern_grid",
	"refinedstorage:orange_controller",
	"refinedstorage:orange_crafter",
	"refinedstorage:orange_crafter_manager",
	"refinedstorage:orange_crafting_monitor",
	"refinedstorage:orange_fluid_grid",
	"refinedstorage:orange_pattern_grid",
	"refinedstorage:pattern",
	"refinedstorage:pattern_grid",
	"refinedstorage:pink_controller",
	"refinedstorage:pink_crafter",
	"refinedstorage:pink_crafter_manager",
	"refinedstorage:pink_crafting_monitor",
	"refinedstorage:pink_fluid_grid",
	"refinedstorage:pink_pattern_grid",
	"refinedstorage:portable_grid",
	"refinedstorage:purple_controller",
	"refinedstorage:purple_crafter",
	"refinedstorage:purple_crafter_manager",
	"refinedstorage:purple_crafting_monitor",
	"refinedstorage:purple_fluid_grid",
	"refinedstorage:purple_pattern_grid",
	"refinedstorage:red_controller",
	"refinedstorage:red_crafter",
	"refinedstorage:red_crafter_manager",
	"refinedstorage:red_crafting_monitor",
	"refinedstorage:red_fluid_grid",
	"refinedstorage:red_pattern_grid",
	"refinedstorage:silk_touch_upgrade",
	"refinedstorage:storage_monitor",
	"refinedstorage:white_controller",
	"refinedstorage:white_crafter",
	"refinedstorage:white_crafter_manager",
	"refinedstorage:white_crafting_monitor",
	"refinedstorage:white_fluid_grid",
	"refinedstorage:white_pattern_grid",
	"refinedstorage:wireless_crafting_monitor",
	"refinedstorage:wireless_fluid_grid",
	"refinedstorage:wireless_grid",
	"refinedstorage:yellow_controller",
	"refinedstorage:yellow_crafter",
	"refinedstorage:yellow_crafter_manager",
	"refinedstorage:yellow_crafting_monitor",
	"refinedstorage:yellow_fluid_grid",
	"refinedstorage:yellow_pattern_grid",
	"refinedstorageaddons:wireless_crafting_grid",
	"simplehats:aegishat",
	"simplehats:alienphil",
	"simplehats:amalgalichhat",
	"simplehats:angrymask",
	"simplehats:astronaut",
	"simplehats:azumanga_hat",
	"simplehats:bandanargb",
	"simplehats:baseballeaster",
	"simplehats:baseballhat",
	"simplehats:baseballhatfestive",
	"simplehats:baseballhatjuly",
	"simplehats:baseballhatrgb",
	"simplehats:beanieeaster",
	"simplehats:beaniefestive",
	"simplehats:beaniergb",
	"simplehats:binky",
	"simplehats:burgerhat",
	"simplehats:burning_m_bison",
	"simplehats:camera",
	"simplehats:camerabeard",
	"simplehats:candycane",
	"simplehats:cardboard_box",
	"simplehats:cat_hat",
	"simplehats:christmascakehat",
	"simplehats:christmastree",
	"simplehats:cowboyrgb",
	"simplehats:cuphead",
	"simplehats:dairyqueen",
	"simplehats:dangereqsue",
	"simplehats:dangeresquejuly",
	"simplehats:dejiko",
	"simplehats:digger",
	"simplehats:dimmahat",
	"simplehats:discoball",
	"simplehats:disguise",
	"simplehats:doctorhat",
	"simplehats:dorkglassesandteeth",
	"simplehats:doubletake",
	"simplehats:drinkinhat",
	"simplehats:dumhat",
	"simplehats:festiveantlers",
	"simplehats:fireworks",
	"simplehats:flagjuly",
	"simplehats:hat_of_discipline",
	"simplehats:headbolts",
	"simplehats:headphonesblue",
	"simplehats:hockeymask",
	"simplehats:holyhead",
	"simplehats:julydouble",
	"simplehats:lil_termagant",
	"simplehats:megamanhat",
	"simplehats:milady_doll",
	"simplehats:mistletoe",
	"simplehats:nyan_doll",
	"simplehats:peppino",
	"simplehats:pinhead",
	"simplehats:policebucket",
	"simplehats:policesiren",
	"simplehats:poofballhat",
	"simplehats:popehat",
	"simplehats:presentsstack",
	"simplehats:propelhat",
	"simplehats:puchiko",
	"simplehats:rabi_en_rose",
	"simplehats:ranahat",
	"simplehats:rednose",
	"simplehats:redstache",
	"simplehats:rgbbigribbon",
	"simplehats:rgbbowler",
	"simplehats:rgbdragonskull",
	"simplehats:rgbdrinkinhat",
	"simplehats:rgbeasterhead",
	"simplehats:rgbfullhelm",
	"simplehats:rgbsmallbowler",
	"simplehats:rgbsunglasses",
	"simplehats:rgbtoptophathat",
	"simplehats:rgbushanka",
	"simplehats:rubbernipple",
	"simplehats:santaclaus",
	"simplehats:scouter",
	"simplehats:shakehat",
	"simplehats:simsgem",
	"simplehats:sleepeyemask",
	"simplehats:sonichood",
	"simplehats:sport_sunglasses",
	"simplehats:springer",
	"simplehats:stinkycheeseman",
	"simplehats:stuck_lollipop",
	"simplehats:sunglasses",
	"simplehats:sunglassesbig",
	"simplehats:supersandhat",
	"simplehats:swimmer",
	"simplehats:the_noise",
	"simplehats:the_noisier",
	"simplehats:thumbnail",
	"simplehats:tick_on_head",
	"simplehats:toilet",
	"simplehats:toy_story_alien",
	"simplehats:traffic_cone",
	"simplehats:triangleshades",
	"simplehats:tvhead",
	"simplehats:twilight_doll",
	"simplehats:udder_hat",
	"simplehats:worms_mine",
	"sophisticatedbackpacks:advanced_deposit_upgrade",
	"sophisticatedbackpacks:advanced_pump_upgrade",
	"sophisticatedbackpacks:battery_upgrade",
	"sophisticatedbackpacks:deposit_upgrade",
	"sophisticatedbackpacks:inception_upgrade",
	"sophisticatedbackpacks:pump_upgrade",
	"sophisticatedbackpacks:stack_upgrade_tier_2",
	"sophisticatedbackpacks:stack_upgrade_tier_3",
	"sophisticatedbackpacks:stack_upgrade_tier_4",
	"sophisticatedstorage:advanced_feeding_upgrade",
	"sophisticatedstorage:advanced_pump_upgrade",
	"sophisticatedstorage:copper_shulker_box",
	"sophisticatedstorage:debug_tool",
	"sophisticatedstorage:diamond_shulker_box",
	"sophisticatedstorage:feeding_upgrade",
	"sophisticatedstorage:gold_shulker_box",
	"sophisticatedstorage:iron_shulker_box",
	"sophisticatedstorage:jukebox_upgrade",
	"sophisticatedstorage:netherite_shulker_box",
	"sophisticatedstorage:pump_upgrade",
	"sophisticatedstorage:shulker_box",
	"sophisticatedstorage:xp_pump_upgrade",
	"structure_gel:blue_gel",
	"structure_gel:building_tool",
	"structure_gel:cyan_gel",
	"structure_gel:data_handler",
	"structure_gel:dynamic_spawner",
	"structure_gel:green_gel",
	"structure_gel:orange_gel",
	"structure_gel:red_gel",
	"structure_gel:yellow_gel",
	"supplementaries:rope",
	"twilightdelight:cooked_venison_rib",
	"twilightdelight:raw_venison_rib",
	"twilightforest:charm_of_keeping_1",
	"twilightforest:charm_of_keeping_2",
	"twilightforest:charm_of_keeping_3",
	"twilightforest:cooked_venison",
	"twilightforest:raw_venison",
	"extradelight:fried_brains",
	"extradelight:liver_onions",
	"extradelight:sextuple_meat_treat",
	"extradelight:oxtail_soup",
	"extradelight:haggis_block_item",
	"extradelight:haggis",
	"refurbished_furniture:oak_mail_box",
	"refurbished_furniture:spruce_mail_box",
	"refurbished_furniture:birch_mail_box",
	"refurbished_furniture:jungle_mail_box",
	"refurbished_furniture:acacia_mail_box",
	"refurbished_furniture:dark_oak_mail_box",
	"refurbished_furniture:mangrove_mail_box",
	"refurbished_furniture:crimson_mail_box",
	"refurbished_furniture:warped_mail_box",
	"refurbished_furniture:post_box",
	"ars_instrumentum:numeric_mana_charm",
	"spelunkery:raw_lead_nugget",
	"spelunkery:raw_silver_nugget",
	"spelunkery:copper_nugget",
	"spelunkery:rough_jade_shard",
	"spelunkery:jade_shard",
	"delightful:steel_knife",
	"delightful:silver_knife",
	"delightful:bronze_knife",
	"alexsmobs:mimicream",
	"hexerei:willow_woodcutter",
];
//MARK: AE2 Disabled Items
global.ae2_disabled_items = [
	"ae2:matter_ball",
	"ae2:matter_cannon",
	"ae2:light_gray_lumen_paint_ball",
	"ae2:cyan_lumen_paint_ball",
	"ae2:purple_lumen_paint_ball",
	"ae2:blue_lumen_paint_ball",
	"ae2:brown_lumen_paint_ball",
	"ae2:green_lumen_paint_ball",
	"ae2:black_lumen_paint_ball",
	"ae2:red_lumen_paint_ball",
	"ae2:white_lumen_paint_ball",
	"ae2:orange_lumen_paint_ball",
	"ae2:magenta_lumen_paint_ball",
	"ae2:light_blue_lumen_paint_ball",
	"ae2:yellow_lumen_paint_ball",
	"ae2:lime_lumen_paint_ball",
	"ae2:pink_lumen_paint_ball",
	"ae2:gray_lumen_paint_ball",
	"ae2:logic_processor_press",
	"ae2:engineering_processor_press",
	"ae2:calculation_processor_press",
	"ae2:printed_logic_processor",
	"ae2:printed_engineering_processor",
	"ae2:printed_calculation_processor",
	"ae2:engineering_processor",
	"ae2:calculation_processor",
	"ae2:logic_processor",
	"ae2:silicon_press",
	"ae2:crafting_card",
	"ae2:spatial_cell_component_2",
	"ae2:spatial_cell_component_16",
	"ae2:spatial_cell_component_128",
	"ae2:spatial_storage_cell_2",
	"ae2:spatial_storage_cell_16",
	"ae2:spatial_storage_cell_128",
	"ae2:spatial_pylon",
	"ae2:spatial_anchor",
	"ae2:spatial_io_port",
	"ae2:pattern_provider",
	"ae2:cable_pattern_provider",
	"ae2:1k_crafting_storage",
	"ae2:4k_crafting_storage",
	"ae2:16k_crafting_storage",
	"ae2:64k_crafting_storage",
	"ae2:256k_crafting_storage",
	"ae2:crafting_monitor",
	"ae2:molecular_assembler",
	"ae2:energy_acceptor",
	"ae2:energy_cell",
	"ae2:dense_energy_cell",
	"ae2:energy_level_emitter",
	"ae2:cable_energy_acceptor",
	"ae2:fe_p2p_tunnel",
	"ae2:pattern_access_terminal",
	"ae2:not_so_mysterious_cube",
	"ae2:condenser",
	"ae2:crafting_accelerator",
	"ae2:silicon",
	"ae2:printed_silicon",
	"ae2:crafting_unit",
	"ae2:charger",
	"ae2:blank_pattern",
	"ae2:growth_accelerator",
	"ae2:inscriber",
	"ae2:name_press",
	"ae2:pattern_encoding_terminal",
	"ae2:sky_stone_chest",
	"ae2:smooth_sky_stone_chest",
	"ae2:mysterious_cube",
	"ae2:vibration_chamber",
	"ae2:memory_card_white",
	"ae2:memory_card_orange",
	"ae2:memory_card_magenta",
	"ae2:memory_card_light_blue",
	"ae2:memory_card_yellow",
	"ae2:memory_card_lime",
	"ae2:memory_card_pink",
	"ae2:memory_card_gray",
	"ae2:memory_card_light_gray",
	"ae2:memory_card_cyan",
	"ae2:memory_card_purple",
	"ae2:memory_card_blue",
	"ae2:memory_card_brown",
	"ae2:memory_card_green",
	"ae2:memory_card_red",
	"ae2:memory_card_black",
	"ae2:white_paint_ball",
	"ae2:orange_paint_ball",
	"ae2:magenta_paint_ball",
	"ae2:blue_paint_ball",
	"ae2:purple_paint_ball",
	"ae2:cyan_paint_ball",
	"ae2:light_gray_paint_ball",
	"ae2:gray_paint_ball",
	"ae2:pink_paint_ball",
	"ae2:lime_paint_ball",
	"ae2:yellow_paint_ball",
	"ae2:light_blue_paint_ball",
	"ae2:brown_paint_ball",
	"ae2:green_paint_ball",
	"ae2:red_paint_ball",
	"ae2:black_paint_ball",
	"ae2:guide",
	"ae2:purple_smart_dense_cable",
	"ae2:blue_smart_dense_cable",
	"ae2:brown_smart_dense_cable",
	"ae2:green_smart_dense_cable",
	"ae2:red_smart_dense_cable",
	"ae2:black_smart_dense_cable",
	"ae2:fluix_smart_dense_cable",
	"ae2:orange_smart_dense_cable",
	"ae2:magenta_smart_dense_cable",
	"ae2:light_blue_smart_dense_cable",
	"ae2:yellow_smart_dense_cable",
	"ae2:lime_smart_dense_cable",
	"ae2:pink_smart_dense_cable",
	"ae2:gray_smart_dense_cable",
	"ae2:light_gray_smart_dense_cable",
	"ae2:cyan_smart_dense_cable",
	"ae2:white_smart_dense_cable",
	"ae2:fluix_covered_dense_cable",
	"ae2:black_covered_dense_cable",
	"ae2:red_covered_dense_cable",
	"ae2:green_covered_dense_cable",
	"ae2:brown_covered_dense_cable",
	"ae2:blue_covered_dense_cable",
	"ae2:purple_covered_dense_cable",
	"ae2:cyan_covered_dense_cable",
	"ae2:white_covered_dense_cable",
	"ae2:orange_covered_dense_cable",
	"ae2:magenta_covered_dense_cable",
	"ae2:light_blue_covered_dense_cable",
	"ae2:yellow_covered_dense_cable",
	"ae2:lime_covered_dense_cable",
	"ae2:pink_covered_dense_cable",
	"ae2:gray_covered_dense_cable",
	"ae2:light_gray_covered_dense_cable",
	"ae2:white_glass_cable",
	"ae2:orange_glass_cable",
	"ae2:magenta_glass_cable",
	"ae2:light_blue_glass_cable",
	"ae2:yellow_glass_cable",
	"ae2:lime_glass_cable",
	"ae2:pink_glass_cable",
	"ae2:gray_glass_cable",
	"ae2:fluix_glass_cable",
	"ae2:black_glass_cable",
	"ae2:red_glass_cable",
	"ae2:green_glass_cable",
	"ae2:brown_glass_cable",
	"ae2:blue_glass_cable",
	"ae2:purple_glass_cable",
	"ae2:cyan_glass_cable",
	"ae2:light_gray_glass_cable",
	"ae2:fluix_smart_cable",
	"ae2:black_smart_cable",
	"ae2:pink_smart_cable",
	"ae2:gray_smart_cable",
	"ae2:light_gray_smart_cable",
	"ae2:cyan_smart_cable",
	"ae2:purple_smart_cable",
	"ae2:blue_smart_cable",
	"ae2:brown_smart_cable",
	"ae2:green_smart_cable",
	"ae2:red_smart_cable",
	"ae2:lime_smart_cable",
	"ae2:yellow_smart_cable",
	"ae2:light_blue_smart_cable",
	"ae2:magenta_smart_cable",
	"ae2:orange_smart_cable",
	"ae2:white_smart_cable",
	"ae2wtlib:wireless_pattern_encoding_terminal",
	"ae2wtlib:wireless_pattern_access_terminal",
	"ae2:meteorite_compass",
	"ae2:charged_staff",
	"ae2:color_applicator",
	"ae2:entropy_manipulator",
	"ae2:certus_quartz_axe",
	"ae2:certus_quartz_hoe",
	"ae2:certus_quartz_shovel",
	"ae2:nether_quartz_sword",
	"ae2:nether_quartz_pickaxe",
	"ae2:nether_quartz_shovel",
	"ae2:nether_quartz_hoe",
	"ae2:nether_quartz_axe",
	"ae2:certus_quartz_sword",
	"ae2:certus_quartz_pickaxe",
	"ae2:nether_quartz_cutting_knife",
	"ae2wtlib:magnet_card",
	"ae2:controller",
	"ae2:crank",
	"ae2:wireless_terminal",
];

/**
 * MARK: Hidden Items
 * These items are hidden from JEI, but are not marked as unobtainable
 */
global.hidden_items = [
	"artifacts:feral_claws",
	"artifacts:flippers",
	"artifacts:golden_hook",
	"artifacts:helium_flamingo",
	"artifacts:snorkel",
	"artifacts:umbrella",
	"kubejs:pink_moon",
	"kubejs:flower_moon",
	"kubejs:strawberry_moon",
	"kubejs:antler_moon",
	"kubejs:harvest_moon",
	"kubejs:corn_moon",
	"kubejs:oak_moon",
	"kubejs:hunter_moon",
	"kubejs:wolf_moon",
	"kubejs:frost_moon",
	"kubejs:snow_moon",
	"kubejs:worm_moon",
	"kubejs:black_moon",
];
