//priority: 100
ServerEvents.recipes((event) => {
	// All Recipe Removal
	let toRemove = [
		//Removed Recipes
		{ id: "netherdepthsupgrade:eyeball" },
		{ id: "netherdepthsupgrade:fortress_grouper_plate" },
		{ mod: "mcsa" },
		{ mod: "plushies" },
		{ output: "alexsmobs:transmutation_table" },
		{ output: "artifacts:feral_claws" },
		{ output: "artifacts:flippers" },
		{ output: "artifacts:golden_hook" },
		{ output: "artifacts:helium_flamingo" },
		{ output: "artifacts:snorkel" },
		{ output: "artifacts:umbrella" },
		{ output: "backpacked:backpack" },
		{ output: "buildinggadgets:gadget_building" },
		{ output: "buildinggadgets:gadget_copy_paste" },
		{ output: "buildinggadgets:gadget_destruction" },
		{ output: "buildinggadgets:gadget_exchanging" },
		{ output: "buildinggadgets:template_manager" },
		{ output: "charginggadgets:charging_station" },
		{ output: "comforts:sleeping_bag_black" },
		{ output: "comforts:sleeping_bag_blue" },
		{ output: "comforts:sleeping_bag_brown" },
		{ output: "comforts:sleeping_bag_cyan" },
		{ output: "comforts:sleeping_bag_gray" },
		{ output: "comforts:sleeping_bag_green" },
		{ output: "comforts:sleeping_bag_light_blue" },
		{ output: "comforts:sleeping_bag_light_gray" },
		{ output: "comforts:sleeping_bag_lime" },
		{ output: "comforts:sleeping_bag_magenta" },
		{ output: "comforts:sleeping_bag_orange" },
		{ output: "comforts:sleeping_bag_pink" },
		{ output: "comforts:sleeping_bag_purple" },
		{ output: "comforts:sleeping_bag_red" },
		{ output: "comforts:sleeping_bag_white" },
		{ output: "comforts:sleeping_bag_yellow" },
		{ output: "crittersandcompanions:pearl_necklace_2" },
		{ output: "crittersandcompanions:pearl_necklace_3" },
		{ output: "deeperdarker:soul_elytra" },
		{ output: "delightful:cheeseburger" },
		{ output: "delightful:deluxe_cheeseburger" },
		{ output: "farmersdelight:hamburger" },
		{ output: "farmersdelight:organic_compost" },
		{ output: "luphieclutteredmod:luphie_sewing_table_clutter" },
		{ output: "luphieclutteredmod:small_shelf" },
		{ output: "mermod:moon_rock_modifier" },
		{ output: "mermod:sea_crystal" },
		{ output: "minecraft:coal" },
		{ output: "minecraft:lodestone" },
		{ output: "minecraft:milk_bucket" },
		{ output: "minecraft:mushroom_stew" },
		{ output: "miners_delight:sticky_basket" },
		{ output: "naturescompass:naturescompass" },
		{ output: "nethersdelight:blackstone_blast_furnace" },
		{ output: "pipez:item_pipe" },
		{ output: "refinedstorage:cable" },
		{ output: "refinedstorage:network_receiver" },
		{ output: "refinedstorage:network_transmitter" },
		{ output: "refinedstorage:quartz_enriched_iron" },
		{ output: "refinedstorage:storage_housing" },
		{ output: "refinedstorage:upgrade" },
		{ output: "ring_of_enderchest:ring_of_enderchest" },
		{ output: "rsinfinitybooster:dimension_card" },
		{ output: "rsinfinitybooster:infinity_card" },
		{ output: "sophisticatedbackpacks:backpack" },
		{ output: "sophisticatedbackpacks:xp_pump_upgrade" },
		{ output: "spelunkery:coal_lump" },
		{ output: "spelunkery:glowstick" },
		{ output: "tarotcards:tarot_deck" },
		{ output: "tiab:time_in_a_bottle" },
		{ id: "extradelight:chicken_patty" },
		{ id: "hexerei:leather_from_drying_rack" },
		{ id: "create:crafting/tree_fertilizer" }, // this is the buggy recipe with the missing tag / barrier block
		{ id: "extradelight:vinegar_pot_potion" }, // allows uncrafting into uncraftable potion, not much point anyways when you can just use a water bucket
		{ id: "extradelight:cactus_juice" },
		{ id: "culturaldelights:cutting/corn_kernels" },
		{ id: "culturaldelights:cutting/corn_kernels_using_deployer" },
		{ id: "refurbished_furniture:constructing/crimson_mail_box" },
		{ id: "refurbished_furniture:constructing/warped_mail_box" },
		{ id: "refurbished_furniture:constructing/mangrove_mail_box" },
		{ id: "refurbished_furniture:constructing/dark_oak_mail_box" },
		{ id: "refurbished_furniture:constructing/acacia_mail_box" },
		{ id: "refurbished_furniture:constructing/jungle_mail_box" },
		{ id: "refurbished_furniture:constructing/birch_mail_box" },
		{ id: "refurbished_furniture:constructing/spruce_mail_box" },
		{ id: "refurbished_furniture:constructing/oak_mail_box" },
		{ id: "refurbished_furniture:constructing/post_box" },
		{ id: "create:milling/compat/botania/black_petal" }, // Removal of Botania compat causing removed tags to appear in JEI
		{ id: "create:milling/compat/botania/blue_petal" },
		{ id: "create:milling/compat/botania/brown_petal" },
		{ id: "create:milling/compat/botania/cyan_petal" },
		{ id: "create:milling/compat/botania/gray_petal" },
		{ id: "create:milling/compat/botania/green_petal" },
		{ id: "create:milling/compat/botania/light_blue_petal" },
		{ id: "create:milling/compat/botania/light_gray_petal" },
		{ id: "create:milling/compat/botania/lime_petal" },
		{ id: "create:milling/compat/botania/magenta_petal" },
		{ id: "create:milling/compat/botania/orange_petal" },
		{ id: "create:milling/compat/botania/pink_petal" },
		{ id: "create:milling/compat/botania/purple_petal" },
		{ id: "create:milling/compat/botania/red_petal" },
		{ id: "create:milling/compat/botania/white_petal" },
		{ id: "create:milling/compat/botania/yellow_petal" },
		{ id: "create:crushing/compat/byg/lignite_ore" }, //Removal of lignite compat with missing tag / barrier block
		{ id: "alexsmobs:hemolymph_blaster" },
		{ id: "create:mixing/whippedcream_bucket_create"},
		{ id: "create:mixing/whippedcream_bottle_create"}
	];

	for (const remove of toRemove) {
		event.remove(remove);
	}
});
